---
- hosts: all
  become: true
  tasks:
    - name: Install required packages
      yum:
        name:
          - docker
          - git
          - java-1.8.0-amazon-corretto
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Jenkins
      shell: |
        wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
        rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        yum install -y jenkins
      notify: restart jenkins

    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: true

    - name: Install Grafana
      shell: |
        yum install -y https://dl.grafana.com/oss/release/grafana-8.5.0-1.x86_64.rpm
      notify: restart grafana

  handlers:
    - name: restart jenkins
      service:
        name: jenkins
        state: restarted
    - name: restart grafana
      service:
        name: grafana-server
        state: restarted
